FactoryGirl.define do
  factory :role do
    name 'member'
    initialize_with { Role.find_or_create_by(name: name) }
  end

  factory :user do
    sequence(:email) { |n| "user_#{n}@cookery.com" }
    password 'qwerasdf'

    roles { [FactoryGirl.create(:role)] }
  end

  factory :ingredient do
    sequence(:name) { |n| "Ingredient[#{n}]" }
    found_at 'Rewe'
  end

  factory :quantity do |q|
    unit 'pinch'
    amount 1

    q.association :ingredient

    factory :quantity_tablespoon do
      unit 'tablespoon'
      amount 2
    end
  end

  factory :category do
    sequence(:name) { |n| "Category[#{n}]" }
  end

  factory :picture do
    sequence(:caption) { |n| "Picture[#{n}]" }
    photo { Rails.root.join('spec', 'fixtures', 'pan.png').open }
  end

  factory :video do
    sequence(:url) { |n| "https://youtube.com/watch?v=#{n}"}
  end

  factory :step do

    notes 'Generated by Factory'

    factory :step_last do
      name 'rest'
      duration 5.minutes
    end

    factory :step_cook do
      name 'cook'
      duration 15.minutes

      quantities { FactoryGirl.create_list(:quantity, 3) }
    end

    factory :step_first do
      name 'prepare'
      duration 10.minutes

      quantities { FactoryGirl.create_list(:quantity_tablespoon, 3) }
    end

  end

  factory :recipe do
    author { FactoryGirl.create(:user) }
    sequence(:name) { |n| "Recipe[#{n}]" }
    difficulty 'medium'

    categories { FactoryGirl.create_list(:category, 3) }

    steps { [FactoryGirl.create(:step_last)] }

    videos { FactoryGirl.create_list(:video, 3) }

    factory :recipe_multi_step do
      steps { [:step_first, :step_cook, :step_last].map { |s| FactoryGirl.create(s) }}
    end

    # Warning: VERY slow
    factory :recipe_with_pictures do
      pictures { FactoryGirl.create_list(:picture, 3) }
    end

    after :build do |r|
      r.steps.map do |step|
        step.recipe = r
        step.save
      end
    end
  end
end
