FactoryGirl.define do
  factory :ingredient do
    sequence(:name) { |n| "Ingredient[#{n}]" }
    found_at 'Rewe'
  end

  factory :quantity do |q|
    unit 'pinch'
    amount 1

    q.association :ingredient
  end

  factory :category do
    sequence(:name) { |n| "Category[#{n}]" }
  end

  factory :picture do
    sequence(:caption) { |n| "Picture[#{n}]" }
    photo { Rails.root.join('spec', 'fixtures', 'pan.png').open }
  end

  factory :step do

    notes 'Generated by Factory'

    factory :step_last do
      name 'rest'
      duration 5.minutes
    end

    factory :step_cook do |s|
      name 'cook'
      duration 15.minutes

      s.quantities { |q| [q.association(:quantity)] }
    end

    factory :step_first do
      name 'prepare'
      duration 10.minutes
    end

  end

  factory :recipe do
    sequence(:name) { |n| "Recipe[#{n}]" }
    difficulty 'medium'

    categories { FactoryGirl.create_list(:category, 3) }

    steps { [FactoryGirl.create(:step_last)] }

    factory :recipe_multi_step do
      steps { [:step_first, :step_cook, :step_last].map { |s| FactoryGirl.create(s) }}
    end

    # Warning: VERY slow
    factory :recipe_with_pictures do
      pictures { FactoryGirl.create_list(:picture, 3) }
    end

    after :build do |r|
      r.steps.map do |step|
        step.recipe = r
        step.save
      end
    end
  end
end
